
package server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ShoppingCartService", targetNamespace = "http://server/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ShoppingCartService {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://server/ShoppingCartService/buyRequest", output = "http://server/ShoppingCartService/buyResponse")
    public boolean buy(
        @WebParam(name = "arg0", partName = "arg0")
        long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://server/ShoppingCartService/identifyRequest", output = "http://server/ShoppingCartService/identifyResponse")
    public long identify(
        @WebParam(name = "arg0", partName = "arg0")
        long arg0);

    /**
     * 
     * @return
     *     returns server.Stock
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://server/ShoppingCartService/getStockRequest", output = "http://server/ShoppingCartService/getStockResponse")
    public Stock getStock();

    /**
     * 
     * @param arg0
     * @return
     *     returns server.ShoppingCart
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://server/ShoppingCartService/getShoppingCartRequest", output = "http://server/ShoppingCartService/getShoppingCartResponse")
    public ShoppingCart getShoppingCart(
        @WebParam(name = "arg0", partName = "arg0")
        long arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://server/ShoppingCartService/addProductToShoppingCartRequest", output = "http://server/ShoppingCartService/addProductToShoppingCartResponse")
    public void addProductToShoppingCart(
        @WebParam(name = "arg0", partName = "arg0")
        long arg0,
        @WebParam(name = "arg1", partName = "arg1")
        long arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://server/ShoppingCartService/clearShoppingCartRequest", output = "http://server/ShoppingCartService/clearShoppingCartResponse")
    public void clearShoppingCart(
        @WebParam(name = "arg0", partName = "arg0")
        long arg0);

}
